services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /var/www/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - mysql
    networks:
      - laravel_dev

  vite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_vite
    restart: unless-stopped
    working_dir: /var/www
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www
      - /var/www/node_modules
    networks:
      - laravel_dev


  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sistem_laundry_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - laravel_dev


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - laravel_dev

networks:
  laravel_dev:
    driver: bridge

volumes:
  mysql_dev_data:
  redis_dev_data:
