[phases.setup]
nixPkgs = ["php83", "php83Extensions.intl", "php83Extensions.zip", "php83Extensions.gd", "php83Extensions.pdo_mysql", "php83Extensions.redis"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "npm install",
  "npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && frankenphp run --config /Caddyfile"  